CREATE TABLE thesis_forms (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  FileUrl VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  VersionNumber INT NOT NULL DEFAULT 1,
  UploadedBy INT NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (UploadedBy) REFERENCES users(UserID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE thesis_form_histories (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  ThesisFormId INT NOT NULL,
  FileUrl VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  VersionNumber INT NOT NULL,
  UploadedBy INT NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ThesisFormId) REFERENCES thesis_forms(Id),
  FOREIGN KEY (UploadedBy) REFERENCES users(UserID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
