-- Migration: V45__Add_Reporting_Fields_To_Thesis.sql
ALTER TABLE `thesis`
ADD COLUMN `ThesisNameEn` VARCHAR(512) NULL,
ADD COLUMN `ThesisNameVi` VARCHAR(512) NULL,
ADD COLUMN `Abbreviation` VARCHAR(10) NULL,
ADD COLUMN `IsFromEnterprise` TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN `EnterpriseName` VARCHAR(255) NULL,
ADD COLUMN `IsApplied` TINYINT(1) NOT NULL DEFAULT 0,
ADD COLUMN `IsAppUsed` TINYINT(1) NOT NULL DEFAULT 0;
