-- Migration to make Thesis.UserId nullable and add REVISION_UPDATED event type
ALTER TABLE thesis MODIFY COLUMN UserId INT NULL;
ALTER TABLE thesis_review_events MODIFY COLUMN EventType ENUM('REVIEWER_ASSIGNED','REVIEWER_DECISION','FINAL_DECISION','COMMENT_ADDED','COMMENT_EDITED','STATUS_CHANGED','SYSTEM','REVISION_UPDATED');
