CREATE TABLE thesis_histories (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  ThesisId VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  FileUrl VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  VersionNumber INT NOT NULL DEFAULT 1,
  Note TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  UploadedBy INT NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ThesisId) REFERENCES thesis(ThesisId),
  FOREIGN KEY (UploadedBy) REFERENCES users(UserId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
