name: ASP.NET Web API CI (Test)

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: Test
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 5s --health-timeout 5s --health-retries 6

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.417"

      - name: Restore all projects
        run: dotnet restore

      - name: Build API (builds dependencies automatically)
        run: |
          dotnet build CapstoneProject_BE/capstone_be.csproj \
            --configuration Release \
            --no-restore

      - name: Test
        env:
          REDIS_CONNECTION: "localhost:6379,abortConnect=False"
        run: |
          echo "Waiting for Redis to be available..."
          sudo apt-get update -y && sudo apt-get install -y redis-tools
          for i in {1..30}; do
            if redis-cli -h localhost ping | grep -q PONG; then
              echo "Redis is up"; break
            fi
            echo "Redis not ready yet, waiting..."; sleep 1
          done
          dotnet test FCTMS.Tests/FCTMS.Tests.csproj \
            --configuration Release \
            --verbosity normal
  deploy-test:
    needs: build-test
    runs-on: ubuntu-latest
    environment: Test

    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---- Docker ----
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/capstone_be:2.0 .
          docker push ${{ secrets.DOCKER_USERNAME }}/capstone_be:2.0

      # ---- Azure ----
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP }} \
            --resource-group capstoneResourceGroupNew \
            --image docker.io/${{ secrets.DOCKER_USERNAME }}/capstone_be:2.0
